--- #YAML:1.0
name:               Wx-Perl-Packager
version:            0.27
abstract:           ~
author:
    - Mark Dootson <mdootson@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:  0
    Digest::MD5:      0
    Wx:               0.49
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
